with open('app/globals.css', 'r', encoding='utf-8') as f:
    lines = f.readlines()

# keep up to line 361 (index 361)
lines = lines[:361]

lines.extend([
    "  z-index: 2147483646;\n",
    "}\n",
    "\n",
    "/* Ensure the new generic theme content rests on top, we will animate its clip-path via JS */\n",
    "::view-transition-old(root) {\n",
    "  z-index: 1;\n",
    "}\n",
    "::view-transition-new(root) {\n",
    "  z-index: 2;\n",
    "}\n",
    "\n",
    "/* Reverse z-index for dark mode if we want the dark to reveal the light, but the script usually handles animation on new(root) */\n",
    "/* .dark::view-transition-old(root) { z-index: 2; } */\n",
    "/* .dark::view-transition-new(root) { z-index: 1; } */\n",
    "\n",
    "/* Animated Search Component CSS */\n",
    ".finder-icon {\n",
    "  width: 40px;\n",
    "  height: 40px;\n",
    "  transition: all 0.2s;\n",
    "  box-shadow: inset 0 0 0 20px var(--color-admin-dark);\n",
    "  border-radius: 50%;\n",
    "  position: relative;\n",
    "}\n",
    "\n",
    ".finder-icon::after,\n",
    ".finder-icon::before {\n",
    "  display: block;\n",
    "  content: '';\n",
    "  position: absolute;\n",
    "  transition: all 0.5s cubic-bezier(0.68, -0.55, 0.265, 1.55);\n",
    "}\n",
    "\n",
    ".finder-icon::after {\n",
    "  width: 10px;\n",
    "  height: 10px;\n",
    "  background-color: var(--color-admin-dark);\n",
    "  border: 3px solid var(--color-admin-light);\n",
    "  top: 50%;\n",
    "  transform: translateY(-50%);\n",
    "  left: 0px;\n",
    "  right: 0;\n",
    "  margin: auto;\n",
    "  border-radius: 50%;\n",
    "}\n",
    "\n",
    ".active .finder-icon::after {\n",
    "  border-width: 10px;\n",
    "  background-color: var(--color-admin-light);\n",
    "}\n",
    "\n",
    ".finder-icon::before {\n",
    "  width: 4px;\n",
    "  height: 13px;\n",
    "  background-color: var(--color-admin-light);\n",
    "  top: 50%;\n",
    "  left: 20px;\n",
    "  transform: rotateZ(45deg) translate(-50%, 0);\n",
    "  transform-origin: 0 0;\n",
    "  border-radius: 4px;\n",
    "}\n",
    "\n",
    ".active .finder-icon::before {\n",
    "  background-color: var(--color-admin-dark);\n",
    "  width: 6px;\n",
    "  transform: rotateZ(45deg) translate(-50%, 25px);\n",
    "}\n",
    "\n",
    ".processing .finder-icon {\n",
    "  transform-origin: 50%;\n",
    "  animation: finder-spinner 0.3s linear infinite;\n",
    "  animation-delay: 0.5s;\n",
    "}\n",
    "\n",
    ".active .finder-icon {\n",
    "  transform: translateY(-5px);\n",
    "}\n",
    "\n",
    "@keyframes finder-spinner {\n",
    "  0% { transform: rotateZ(45deg); }\n",
    "  100% { transform: rotateZ(405deg); }\n",
    "}\n"
])

with open('app/globals.css', 'w', encoding='utf-8') as f:
    f.writelines(lines)
